"use client";
import {useEffect,useMemo,useState} from "react";

type Contract={id:string|number;agency:string;state:string;jurisdiction:string;cameraCount?:number;startDate?:string;sourceUrl?:string;status:string};
type Program={id:string;city:string;county:string;state:string;agency:string;vendor:string;summary:string;sourceUrl:string;sourceDate:string};
type Dataset={sourceName:string;license:string;retrievedAt:string;recordCount:number;stateCount:number;programs:Program[]};
type CoverageState={state:string;name:string;total:number;flock:number;otherVendor:number;unknownVendor:number;listedCities:number;documentedPrograms:number;sourceUrl:string};
type Coverage={retrievedAt:string;totalCameras:number;identifiedFlock:number;statesRepresented:number;states:CoverageState[]};

export default function ProgramDashboard({contracts}:{contracts:Contract[]}){
 const [dataset,setDataset]=useState<Dataset|null>(null),[coverage,setCoverage]=useState<Coverage|null>(null),[query,setQuery]=useState(""),[state,setState]=useState("all"),[page,setPage]=useState(1),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();Promise.all([fetch("/api/programs",{signal:controller.signal}),fetch("/api/coverage",{signal:controller.signal})]).then(async responses=>{if(responses.some(r=>!r.ok))throw new Error("National data index unavailable");return Promise.all(responses.map(r=>r.json()))}).then(([programData,coverageData])=>{setDataset(programData);setCoverage(coverageData)}).catch(e=>{if(e.name!=="AbortError")setError(e.message)});return()=>controller.abort()},[]);
 const states=useMemo(()=>[...new Set((dataset?.programs??[]).map(p=>p.state).filter(Boolean))].sort(),[dataset]);
 const matches=useMemo(()=>{const term=query.toLowerCase();return (dataset?.programs??[]).filter(p=>(state==="all"||p.state===state)&&`${p.city} ${p.county} ${p.state} ${p.agency} ${p.vendor} ${p.summary}`.toLowerCase().includes(term))},[dataset,query,state]);
 const pages=Math.max(1,Math.ceil(matches.length/100)),shown=matches.slice((page-1)*100,page*100);
 function changeFilters(action:()=>void){action();setPage(1)}
 return <section className="contracts-page"><div className="section-heading"><div><p className="eyebrow">National deployment intelligence</p><h1>Flock programs & contracts</h1><p>Search documented law-enforcement ALPR programs separately from camera-level community mapping.</p></div><div className="deployment-stats"><div><span>Flock-related programs</span><strong>{dataset?.recordCount??"…"}</strong></div><div><span>States represented</span><strong>{dataset?.stateCount??"…"}</strong></div></div></div>
 <div className="program-controls"><label>Search agencies and places<input value={query} onChange={e=>changeFilters(()=>setQuery(e.target.value))} placeholder="Agency, city, county, or vendor"/></label><label>State<select value={state} onChange={e=>changeFilters(()=>setState(e.target.value))}><option value="all">All states</option>{states.map(value=><option key={value}>{value}</option>)}</select></label></div>
 {error?<p className="admin-message">{error}</p>:!dataset?<p className="empty">Loading the national EFF deployment index…</p>:<><div className="program-summary"><strong>{matches.length.toLocaleString()}</strong> matching documented programs <span>· snapshot {new Date(dataset.retrievedAt).toLocaleDateString()}</span></div><div className="contract-table" role="table"><div className="contract-row program-row header"><span>Agency / jurisdiction</span><span>State</span><span>Vendor</span><span>Evidence summary</span><span>Source</span></div>{shown.map(p=><div className="contract-row program-row" key={p.id}><span><strong>{p.agency}</strong><small>{p.city}{p.county?` · ${p.county}`:""}</small></span><span>{p.state}</span><span>{p.vendor}</span><span className="program-claim">{p.summary}</span><span>{p.sourceUrl?<a href={p.sourceUrl} target="_blank" rel="noreferrer">Review source ↗</a>:"Source unavailable"}<small>{p.sourceDate||p.id}</small></span></div>)}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>← Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>Next →</button></div></>}
 {coverage&&<div className="coverage-section"><div className="coverage-heading"><div><p className="eyebrow">Cross-source coverage</p><h2>Mapped cameras and documented programs by state</h2></div><span>Updated {new Date(coverage.retrievedAt).toLocaleDateString()}</span></div><div className="coverage-table"><div className="coverage-row header"><span>State</span><span>Mapped ALPRs</span><span>Identified Flock</span><span>EFF programs</span><span>Source</span></div>{coverage.states.map(row=><div className="coverage-row" key={row.state}><span><strong>{row.name}</strong><small>{row.listedCities} indexed cities</small></span><span>{row.total.toLocaleString()}</span><span>{row.flock.toLocaleString()} <small>{row.total?Math.round(row.flock/row.total*100):0}% of mapped</small></span><span>{row.documentedPrograms.toLocaleString()}</span><span><a href={row.sourceUrl} target="_blank" rel="noreferrer">Coverage details ↗</a></span></div>)}</div></div>}
 <div className="local-contracts"><h2>Flock Watcher reviewed records</h2>{contracts.map(c=><article key={c.id}><div><strong>{c.agency}</strong><span>{c.jurisdiction}, {c.state}</span></div><span>{c.cameraCount??"—"} cameras</span>{c.sourceUrl&&<a href={c.sourceUrl} target="_blank" rel="noreferrer">Official source ↗</a>}</article>)}</div>
 <p className="data-notice">National program records: Electronic Frontier Foundation Atlas of Surveillance, CC BY. Inclusion documents a reported agency program; it does not establish that equipment remains active or identify exact camera locations.</p></section>
}
