import { env } from "cloudflare:workers";
import { getAdminUser } from "../../admin-auth";
import { ensureSchema } from "../data/route";

async function admin(){return getAdminUser()}

export async function GET(){const user=await admin();if(!user)return Response.json({error:"Administrator access required"},{status:403});await ensureSchema();const sightings=await env.DB.prepare("SELECT id,city,state,latitude,longitude,agency,location,source_url AS sourceUrl,evidence_note AS evidenceNote,status,source_type AS sourceType,submitted_by AS submittedBy,created_at AS createdAt,location_precision AS locationPrecision FROM sightings ORDER BY CASE status WHEN 'submitted' THEN 1 ELSE 2 END,id DESC LIMIT 500").all();const events=await env.DB.prepare("SELECT id,sighting_id AS sightingId,old_status AS oldStatus,new_status AS newStatus,reviewer,note,created_at AS createdAt FROM moderation_events ORDER BY id DESC LIMIT 100").all();const evidence=await env.DB.prepare("SELECT id,sighting_id AS sightingId,original_name AS originalName,mime_type AS mimeType,size_bytes AS sizeBytes,sha256 FROM evidence_files ORDER BY id DESC LIMIT 500").all();return Response.json({sightings:sightings.results,events:events.results,evidence:evidence.results,reviewer:user.displayName})}

export async function PATCH(request:Request){const user=await admin();if(!user)return Response.json({error:"Administrator access required"},{status:403});await ensureSchema();const body=await request.json() as {id?:number;status?:string;note?:string};const allowed=new Set(["submitted","documented","verified","disputed","rejected"]),note=String(body.note??"").trim().slice(0,500);if(!Number.isInteger(body.id)||!body.status||!allowed.has(body.status))return Response.json({error:"A valid record and status are required."},{status:400});if(["verified","rejected"].includes(body.status)&&note.length<8)return Response.json({error:"A reviewer note is required for verification or rejection."},{status:400});const current=await env.DB.prepare("SELECT status,source_url AS sourceUrl,(SELECT COUNT(*) FROM evidence_files WHERE sighting_id=?) AS evidenceCount FROM sightings WHERE id=?").bind(body.id,body.id).first<{status:string;sourceUrl:string|null;evidenceCount:number}>();if(!current)return Response.json({error:"Record not found"},{status:404});if(body.status==="verified"&&!current.sourceUrl&&!Number(current.evidenceCount))return Response.json({error:"Verification requires a public source or uploaded evidence."},{status:400});await env.DB.batch([env.DB.prepare("UPDATE sightings SET status=? WHERE id=?").bind(body.status,body.id),env.DB.prepare("INSERT INTO moderation_events (sighting_id,old_status,new_status,reviewer,note) VALUES (?,?,?,?,?)").bind(body.id,current.status,body.status,user.email,note||null)]);return Response.json({ok:true,id:body.id,status:body.status})}
