import { env } from "cloudflare:workers";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ensureSchema } from "../../api/data/route";
import CorrectionForm from "./correction-form";
export const dynamic="force-dynamic";
type RecordRow={id:number;city:string;state:string;latitude:number;longitude:number;agency:string;location:string;sourceUrl:string|null;evidenceNote:string|null;status:string;sourceType:string;createdAt:string;locationPrecision:string;evidenceCount:number};
async function getRecord(id:number){await ensureSchema();return env.DB.prepare("SELECT s.id,s.city,s.state,s.latitude,s.longitude,s.agency,s.location,s.source_url AS sourceUrl,s.evidence_note AS evidenceNote,s.status,s.source_type AS sourceType,s.created_at AS createdAt,s.location_precision AS locationPrecision,(SELECT COUNT(*) FROM evidence_files e WHERE e.sighting_id=s.id) AS evidenceCount FROM sightings s WHERE s.id=? AND s.status!='rejected'").bind(id).first<RecordRow>()}
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params,record=await getRecord(Number(id));if(!record)return {title:"Record not found | Flock Watcher",robots:{index:false}};const title=`${record.city}, ${record.state} ALPR record | Flock Watcher`,description=`${record.status} ${record.locationPrecision}-precision record attributed to ${record.agency}.`;return {title,description,openGraph:{title,description,images:[]},twitter:{title,description,images:[]}}}
export default async function RecordPage({params}:{params:Promise<{id:string}>}){const {id}=await params,record=await getRecord(Number(id));if(!record)notFound();return <div className="record-page"><header className="record-header"><Link href="/" className="brand"><span className="brand-mark">FW</span><span>Flock Watcher<small>Public evidence record</small></span></Link><Link href="/">← Back to national map</Link></header><main><p className="eyebrow">Public record #{record.id}</p><div className="record-title"><div><h1>{record.city}, {record.state}</h1><p>{record.agency}</p></div><span className={`pill ${record.status}`}>{record.status}</span></div><section className="record-facts"><div><span>Location precision</span><strong>{record.locationPrecision}</strong><p>{record.location}</p></div><div><span>Coordinates</span><strong>{record.latitude.toFixed(4)}, {record.longitude.toFixed(4)}</strong><p>{record.locationPrecision==="jurisdiction"?"These coordinates identify the jurisdiction generally—not a device.":"Precision is reported and subject to evidence review."}</p></div><div><span>Evidence status</span><strong>{record.evidenceCount} private attachment(s)</strong><p>Private evidence is visible only to authorized moderators.</p></div><div><span>Record origin</span><strong>{record.sourceType}</strong><p>Added {record.createdAt}</p></div></section><section className="record-evidence"><p className="eyebrow">Evidence summary</p><h2>What supports this record</h2><p>{record.evidenceNote||"No public evidence summary has been supplied."}</p>{record.sourceUrl&&<a href={record.sourceUrl} target="_blank" rel="noreferrer">Open the public source ↗</a>}</section><CorrectionForm sightingId={record.id}/></main></div>}
